# 生产镜像，仅包含应用代码
ARG BASE_IMAGE=ghcr.io/etnatker/xiaozhi-esp32-server:server-base
# ARG BASE_IMAGE=xiaozhi-esp32-server:server-base
FROM ${BASE_IMAGE}

COPY main/xiaozhi-server .

# 启动应用
CMD ["pixi", "run", "start"]
